join_tournaments/urls.py
from django.contrib import admin
from django.urls import path, include
from tournaments import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.tournament_list),
    path('tournaments/', include('tournaments.urls'))
]

tournaments/urls.py
from django.urls import path
from tournaments import views

app_name = 'tournaments'

urlpatterns = [
    path('tournament_list/', views.tournament_list, name='tournament_list'),
    path('join_tournament/<int:pk>/<str:t_name>/<str:start_date>/<str:end_date>/<str:location>',
         views.join_tournament, name='join_tournament'),
]

tournaments/models.py
from django.db import models

# Create your models here.

tournaments/forms.py
from django import forms


class TournamentJoin(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone_number = forms.IntegerField(required=False)

tournaments/views.py
import json
from django.shortcuts import render, redirect
import requests
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

from tournaments.forms import TournamentJoin


def tournament_list(request):
    url = 'http://127.0.0.1:8000/api/tournaments/'
    response = requests.get(url)
    tournaments = response.json()
    print(tournaments)
    return render(request, 'tournaments/show_tournaments.html', {'tournaments': tournaments})


def join_tournament(request, pk, t_name, start_date, end_date, location):
    if request.method == 'POST':
        form = TournamentJoin(request.POST)
        if form.is_valid():
            url = 'http://127.0.0.1:8000/api/tournaments_join/'
            k = request.POST['pk']
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']

            if form.cleaned_data['phone_number']:
                phone_num = form.cleaned_data['phone_number']
                data = json.dumps({'name': name, 'tournament': k, 'mail': email, 'phoneNumber': phone_num})
                requests.post(url=url, data=data)

            else:
                data = json.dumps({'name': name, 'tournament': k, 'mail': email})
                requests.post(url=url, data=data)

            current_site = get_current_site(request)
            mail_subject = 'SportsHub Tournament Registration Confirmation'
            message = render_to_string('tournaments/activate_email.html', {
                'domain': current_site.domain,
                'user': name,
                'start_date': start_date,
                'end_date': end_date,
                'location': location,
                'tournament_name': t_name
            })
            email = EmailMessage(
                mail_subject, message, to=[email]
            )
            email.send()
            return redirect('tournaments:tournament_list')

        else:
            print('form is invalid')
            print(form.errors)
    else:
        form = TournamentJoin()

    print(int(pk))
    return render(request, 'tournaments/join_tournament.html', {'form': form, 'pk': int(pk)})

tournaments/templates/tournaments/activate_email.html
{% load custom_filters %}

{% autoescape off %}
    Hi {{ user }},
    You have successfully registered for the tournament {{ tournament_name }}
    It's location is {{ location }}
    It starts on {{ start_date|filter_date }} and ends on {{ end_date|filter_date }}

    Thank you for your registration
{% endautoescape %}

tournaments/templates/tournaments/join_tournament.html
{% load widget_tweaks %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>JOIN TOURNAMENTS</title>
	<meta charset="UTF-8">
 <link rel="stylesheet" href="{% static 'tournaments/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/owl.carousel.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/themify-icons.css' %}">
<style>
body {
	background-image: url('{% static "tournaments/img/background.jpg"%}');
    background-repeat:no-repeat;
    background-size:cover;
}

</style>


</head>
<body >

<div class="main" style="padding-top: 180px">
    <div class="container-form">
        <div class="booking-content">
            <div class="booking-form">

                <form method="post" class="booking-form"  >
                    {% csrf_token %}
                    <div class="hero-content" style="padding:0px 0px 30px 0px;  font-size:35px; color: black;">Join Tournaments</div>
                        <div class="form-group form-input">
                            <label class="form-label">
                                 <input class="form-label" type="number" value="{{ pk }}" hidden="true" name="pk">
                            </label>
                                {{ form.as_p }}
                            {% for error in field.errors %}
                                <p style="font-size: 15px; color: red">{{ error }}</p>
                            {% endfor %}
                            <br>
                        </div>

                        <div class="form-submit"  style="padding-left: 110px">
                            <input type="submit"   value="Submit">
                        </div>

                </form>
                    </div>
         </div>
    </div>
</div>
</body>
</html>

tournaments/templates/tournaments/show_tournaments.html
{% load custom_filters %}
{% load widget_tweaks %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

            <h1   style="text-align: center;font-size: 250 px;color: white">List of Tournaments</h1>

    <link rel="stylesheet" href="{% static 'tournaments/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/owl.carousel.css' %}">
        <link rel="stylesheet" href="{% static 'tournaments/css/themify-icons.css' %}">

    <style>
body {

    background-color: darkblue;
    background-repeat:no-repeat;
    background-size:cover;
}

* {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Float four columns side by side */
.column {
  float: left;
  width: 50%;
  padding: 0 10px;
}

/* Remove extra left and right margins, due to padding */
.row {margin: 0 -5px;}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 80%;
    display: block;
    margin-bottom: 20px;
  }
}

/* Style the counter cards */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  background-color: whitesmoke;
}
</style>

</head>
<body style="text-align: center;font-family:Courier New">

<br><br>

 <div class="row">
                {% for tournament in tournaments %}
                <div class="column">
                    <div class="card">
                Name : {{ tournament.name }}<br>
                Description: {{ tournament.description }}<br>
                Location: {{ tournament.location }}<br>
                Start Date: {{ tournament.start_date | filter_date }}<br>
                End Date: {{ tournament.end_date | filter_date }}<br>

                 <h3 >
             <a href="{% url 'tournaments:join_tournament' tournament.pk  tournament.name tournament.start_date tournament.end_date tournament.location %}">
            Click here to join</a></h3>

                     </div>
                <br>
</div>

                {% endfor %}


</div>

</body>
</html>